const level1 = new Level(
    [
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Chicken(),
        // new Endboss(),
        // new SmallChicken(),
        // new SmallChicken(),
        // new SmallChicken(),
        // new SmallChicken(),
        // new SmallChicken(),
    ],

    [
        new Cloud()
    ],
    [
        new BackgroundObject('img/5_background/layers/air.png', -719, 500),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -719, 80),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -719, 80),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -719, 80),
        new BackgroundObject('img/5_background/layers/air.png', 0, 500),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0, 80),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0, 80),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0, 80),
        new BackgroundObject('img/5_background/layers/air.png', 719, 500),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719, 80),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719, 80),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719, 80),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 2, 500),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 719 * 2, 80),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 719 * 2, 80),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 719 * 2, 80),
        new BackgroundObject('img/5_background/layers/air.png', 719 * 3, 500),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 719 * 3, 80),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 719 * 3, 80),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 719 * 3, 80),
    ],
    [
        // new Coin(),
        // new Coin(),
        // new Coin(),
        // new Coin(),
        // new Coin(),
        // new Coin(),
    ],
    [
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
        new Bottle(),
    ]

);